name: KernelSU Build for Moto G31

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # This allows you to trigger the workflow manually from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel with KernelSU
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the kernel source
    - name: Checkout kernel source
      uses: actions/checkout@v3

    # 2. Set up build environment (install dependencies)
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc curl libncurses5-dev libssl-dev git wget ccache flex bison \
                                clang lld libelf-dev libfdt-dev libzstd-dev

    # 3. Download the defconfig file
    - name: Download defconfig
      run: |
        wget -O defconfig https://file.io/ZgXfCU6JAaOc

    # 4. Download KernelSU source and apply it to the kernel
    - name: Clone KernelSU source
      run: |
        git clone https://github.com/tiann/KernelSU.git
        cp -r KernelSU/* .  # Apply KernelSU to your kernel source (adjust based on your repo structure)

    # 5. Set up the Clang toolchain
    - name: Set up toolchain
      run: |
        git clone https://github.com/kdrag0n/proton-clang.git clang
        export PATH="$PWD/clang/bin:$PATH"

    # 6. Configure the kernel with the downloaded defconfig
    - name: Configure kernel
      run: |
        make ARCH=arm64 O=out clean
        make ARCH=arm64 O=out mrproper
        mv defconfig arch/arm64/configs/custom_defconfig
        make ARCH=arm64 O=out custom_defconfig
